logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 43.138.84.176 # RabbitMQ的ip地址
    port: 5678
    virtual-host: /
    username: itcast
    password: 123321
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能取下一条